[project]
name = "GenSBI"
version = "0.0.1"
description = "A JAX implementation of CFM and Diffusion models for generative modeling and SBI."
authors = [{ name = "Aurelio Amerio", email = "aure.amerio@gmail.com" }]
license = "LICENSE"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "jax>=0.4.38",
    "matplotlib>=3.10",
    "numpy>=2.1",
    "flax>=0.6.0",
    "diffrax>=0.6.0",
    "numpyro>=0.16.0",
    "tqdm>=4.62.0",
    "corner>=2.2.3",
    "seaborn>=0.13.2",
    "orbax-checkpoint",
]

[project.urls]
Homepage = "https://github.com/aurelio-amerio/GenSBI"
Issues = "https://github.com/aurelio-amerio/GenSBI/issues"

[project.optional-dependencies]
cuda = ["jax[cuda12]"]
tpu = ["jax[tpu]"]
examples = ["sbibm @ git+https://github.com/sbi-benchmark/sbibm.git"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
force-include = { "src/gen_sbi" = "gen_sbi" }
