[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cfm-jax"
version = "0.0.1"
authors = [
  { name="Aurelio Amerio", email="aurelio.amerio@ific.uv.es" },

]
description = ""
dependencies = [
"numpy",
]
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3"
]

[project.urls]
"Homepage" = "https://github.com/aurelio-amerio/-"
"Bug Tracker" = "https://github.com/aurelio-amerio/-/issues"
