name: CI

on:
  release:
    types: [published]  # Trigger on published releases
  workflow_dispatch:    # Allow manual triggering of the workflow

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v3

    # Build the documentation using Sphinx
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"

    # Create an artifact of the HTML output
    - uses: actions/upload-artifact@v3
      with:
        name: DocumentationHTML
        path: docs/_build/html/

    # Publish built docs to the gh-pages branch
    - name: Commit documentation changes
      run: |
        git clone https://github.com/aurelio-amerio/GenSBI.git --branch gh-pages --single-branch gh-pages
        cp -r docs/_build/html/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # Ignore failure if no changes are present
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}